/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-05-15 14:53:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.util.List;

public final class adminProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/JSP_Servlet_JDBC_MySQL/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hoangkimmobile/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1706523325326L));
    _jspx_dependants.put("jar:file:/D:/JSP_Servlet_JDBC_MySQL/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hoangkimmobile/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi-VN\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0\">\r\n");
      out.write("    <title>Danh sách admin</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"https://hoangkimmobile.com/wp-content/uploads/2021/01/logo-Hoang-Kim-Mobile-retina-xam.png\"\r\n");
      out.write("          sizes=\"192x192\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/plugins/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Fontawesome CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/plugins/fontawesome/css/fontawesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/plugins/fontawesome/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Datatables CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/plugins/datatables/datatables.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Animate CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/animate.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Main CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/admin.css\">\r\n");
      out.write("<style>\r\n");
      out.write("    .modall{\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        z-index: 1000;\r\n");
      out.write("        inset: 0;\r\n");
      out.write("        background-color: rgba(0, 0, 0,0.5);\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("    .modall_container{\r\n");
      out.write("        width: 500px;\r\n");
      out.write("        padding-top: 20px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-cancel{\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 10px;\r\n");
      out.write("        right: 10px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        z-index: 1000000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .n{\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("    .b{\r\n");
      out.write("        display:block;\r\n");
      out.write("    }\r\n");
      out.write("    .form {\r\n");
      out.write("        height: 18em;\r\n");
      out.write("        width: 16em;\r\n");
      out.write("        padding: 4%;\r\n");
      out.write("        border-radius: 16px;\r\n");
      out.write("        background: #e8e8e8;\r\n");
      out.write("        box-shadow: 12px 12px 18px #bababa,\r\n");
      out.write("        -12px -12px 18px #ffffff;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        align-items: stretch;\r\n");
      out.write("        justify-content: space-evenly;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #login-lable {\r\n");
      out.write("        height: 15%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 34px;\r\n");
      out.write("        letter-spacing: 3px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        text-shadow: -2px -2px 3px #ffffff ,\r\n");
      out.write("        2px 2px 3px #bababa;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        top: -14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .input {\r\n");
      out.write("        height: 16%;\r\n");
      out.write("        padding: 1px 8px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        font-size: 1em;\r\n");
      out.write("        letter-spacing: 2px;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        background: #f3f3f3;\r\n");
      out.write("        box-shadow: inset -2px -2px 4px #ffffff,\r\n");
      out.write("        inset 2px 2px 4px rgba(0, 0, 0, 0.356);\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        background: linear-gradient(to right,white, #80808010, white);\r\n");
      out.write("        background-size: 200% 200%;\r\n");
      out.write("        animation: input 4s infinite;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .input:focus-visible {\r\n");
      out.write("        outline: none;\r\n");
      out.write("        background: rgb(241, 241, 241);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #btn {\r\n");
      out.write("        font-size: x-large;\r\n");
      out.write("        letter-spacing: 3px;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        height: 18%;\r\n");
      out.write("        background: linear-gradient(144deg,#af40ff,\r\n");
      out.write("        #5b42f3 50%,#00ddeb);\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        box-shadow: inset 1px 3px 3px #ffffffbd,\r\n");
      out.write("        inset -4px -4px 3px #00000046;\r\n");
      out.write("        background-size: 150% 150%;\r\n");
      out.write("        animation: input 5s infinite;\r\n");
      out.write("        transition: all 900ms ease-in;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #btn:hover {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        bottom: 3px;\r\n");
      out.write("        background: linear-gradient(144deg,#9706ff,\r\n");
      out.write("        #2f0fff 50%,#18f0ff);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes input {\r\n");
      out.write("        0% {\r\n");
      out.write("            background-position: 0% 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        50% {\r\n");
      out.write("            background-position: 100% 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        100% {\r\n");
      out.write("            background-position: 0% 50%;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main-wrapper\">\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"page-wrapper\">\r\n");
      out.write("        <div class=\"content container-fluid\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Page Header -->\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col\">\r\n");
      out.write("                        <h3 class=\"page-title\">Danh sách admin</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto text-right\">\r\n");
      out.write("                        <button class=\"btn btn-primary add-button ml-3\">\r\n");
      out.write("                            <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /Page Header -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table table-hover table-center mb-0 datatable\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th>ID</th>\r\n");
      out.write("                                        <th>Tên</th>\r\n");
      out.write("                                        <th>Email</th>\r\n");
      out.write("                                        <th>Điện thoại</th>\r\n");
      out.write("                                        <th>Quyền</th>\r\n");
      out.write("                                        <th class=\"text-right\">Hành động</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"modall n\">\r\n");
      out.write("        <div class=\"modall_container bg-white\" style=\"margin: auto; margin-top: 10%\">\r\n");
      out.write("            <button class=\"btn btn-link btn-cancel\">X</button>\r\n");
      out.write("            <div class=\"content container-fluid\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div style=\"width: 100%\" class=\"\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Page Header -->\r\n");
      out.write("                        <div class=\"page-header\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col\">\r\n");
      out.write("                                    <h3 class=\"page-title pl-4\">Thêm Admin</h3>\r\n");
      out.write("                                    <ul class=\"breadcrumb pl-4\">\r\n");
      out.write("                                        <li class=\"breadcrumb-item\"><a href=\"admin-list.html\">Danh sách admin</a></li>\r\n");
      out.write("                                        <li class=\"breadcrumb-item active\">Thêm admin</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /Page Header -->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <!-- Form -->\r\n");
      out.write("                                <form action=\"add-admin\" method=\"post\" accept-charset=\"UTF-8\" id=\"login-form\">\r\n");
      out.write("                                    <div class=\"form-group row\">\r\n");
      out.write("                                        <label class=\"col-form-label col-md-3\">Tên người dùng</label>\r\n");
      out.write("                                        <div class=\"col-md-9\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" name=\"username\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group row\">\r\n");
      out.write("                                        <label class=\"col-form-label col-md-3\">Email</label>\r\n");
      out.write("                                        <div class=\"col-md-9\">\r\n");
      out.write("                                            <input type=\"email\" class=\"form-control\" name=\"email\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group row\">\r\n");
      out.write("                                        <label class=\"col-form-label col-md-3\">Mật khẩu</label>\r\n");
      out.write("                                        <div class=\"col-md-9\">\r\n");
      out.write("                                            <input id=\"pass\" type=\"password\" required class=\"form-control\" name=\"pass\">\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group row\">\r\n");
      out.write("                                        <label class=\"col-form-label col-md-3\">Điện thoại</label>\r\n");
      out.write("                                        <div class=\"col-md-9\">\r\n");
      out.write("                                            <input type=\"tel\" class=\"form-control\" name=\"phone\" required>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mt-4\">\r\n");
      out.write("                                        <button style=\"width: 100%\" class=\"btn btn-primary btn-save\" type=\"submit\">Lưu</button>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"./assets/js/jquery-3.5.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core JS -->\r\n");
      out.write("<script src=\"./assets/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"./assets/plugins/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Datatables JS -->\r\n");
      out.write("<script src=\"./assets/plugins/datatables/datatables.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Select2 JS -->\r\n");
      out.write("<script src=\"./assets/js/select2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom JS -->\r\n");
      out.write("<script src=\"./assets/js/admin.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    const modal=document.querySelector(\".modall\");\r\n");
      out.write("    const btn=document.querySelector(\".add-button\");\r\n");
      out.write("    const cancel=document.querySelector(\".btn-cancel\");\r\n");
      out.write("    const save=document.querySelector(\".btn-save\");\r\n");
      out.write("    btn.addEventListener(\"click\",function () {\r\n");
      out.write("        if(modal.classList.contains(\"n\")){\r\n");
      out.write("            modal.classList.remove(\"n\");\r\n");
      out.write("            modal.classList.add(\"b\");\r\n");
      out.write("        }else{\r\n");
      out.write("            modal.classList.remove(\"b\");\r\n");
      out.write("            modal.classList.add(\"n\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    cancel.addEventListener(\"click\",function () {\r\n");
      out.write("        modal.classList.remove(\"b\");\r\n");
      out.write("        modal.classList.add(\"n\");\r\n");
      out.write("    });\r\n");
      out.write("    save.addEventListener(\"click\",function () {\r\n");
      out.write("        modal.classList.remove(\"b\");\r\n");
      out.write("        modal.classList.add(\"n\");\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
